# Generated by Django 4.0 on 2022-01-01 08:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('zipcode', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('dob', models.DateField(max_length=8)),
                ('place_of_birth', models.CharField(max_length=200)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced')], max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('github_link', models.CharField(blank=True, max_length=500, null=True)),
                ('linked_in_link', models.CharField(blank=True, max_length=500, null=True)),
                ('website_link', models.CharField(blank=True, max_length=500, null=True)),
                ('resume_objective', models.TextField()),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
