# Generated by Django 4.0 on 2022-01-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='featured_image',
            field=models.ImageField(default='static/featured_images/Default_Featured_image.jpeg', upload_to='static/featured_images'),
        ),
    ]
