# Generated by Django 4.0 on 2022-01-01 10:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CustomUser', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperince',
            fields=[
                ('job_title', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('employer', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomUser.customuser')),
            ],
        ),
    ]
