# Generated by Django 4.0 on 2022-01-01 11:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0002_alter_customuser_phone_number'),
        ('UserAttachment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('skillfull', 'Skillfull'), ('experinced', 'Experinced'), ('expert', 'Expert')], max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomUser.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='language',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('native', 'Native'), ('professional', 'Professional'), ('medium', 'Good Working Knowledge')], max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomUser.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Intrest',
            fields=[
                ('hobby', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomUser.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('degree', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('institution_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomUser.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='CustomSection',
            fields=[
                ('description', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomUser.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('institute', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomUser.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Achivement',
            fields=[
                ('description', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomUser.customuser')),
            ],
        ),
    ]
